name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildlx64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir build
    - name: configure
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: cmake --build . --config Release -j 4

  buildwin64:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: mkdir build
    - name: configure
      working-directory: build
      run: cmake -G "Visual Studio 16 2019" -A "x64" ..
    - name: make
      working-directory: build
      run: cmake --build . --config Release -j 4
