name: C/C++ CMake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux64:
    name: Build Linux 64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: prepare
      run: mkdir build
    - name: configure
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: cmake --build . --config Release -j 4

  build-win64:
    name: Build Windows 64

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: prepare
      run: mkdir build
    - name: configure
      working-directory: build
      run: cmake -G "Visual Studio 16 2019" -A "x64" ..
    - name: make
      working-directory: build
      run: cmake --build . --config Release -j 4

  build-darwin64:
    name: Build Mac OS X 64

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: prepare
      run: mkdir build
    - name: configure
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: cmake --build . --config Release -j 4
